version: '3'

networks:
  rabbitnet:
    name: rabbitnet
    driver: bridge

services:
  producer:
    build: producer
    networks:
      - rabbitnet
    depends_on:
      - rmq
    restart: on-failure
  consumer:
    build: consumer
    networks:
      - rabbitnet
    depends_on:
      - rmq
    restart: on-failure
  rmq:
    build: rmq
    hostname: rabbitmq
    networks:
      - rabbitnet
    ports:
      # HOST:CONTAINER
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
